---
title: "Codebook"
output:
  md_document:
  toc: true
  toc_depth: 4
  toc_float: true
  code_folding: 'hide'
  self_contained: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually makes debugging easier, and sometimes half a codebook
                # is better than none
  echo = FALSE  # don't show the R code
)
ggplot2::theme_set(ggplot2::theme_bw())
pander::panderOptions("table.split.table", Inf)
```



```{r read in}
abalone_subset <- rio::import( "data/abalone_subset.csv")          
ACIAR <- rio::import( "data/ACIAR.csv")                            
athletes <- rio::import( "data/athletes.csv")                      
autism <- rio::import( "data/autism.csv")                          
biomarker <- rio::import( "data/biomarker.csv")                    
crd_rats_data <- rio::import( "data/crd_rats_data.csv")            
diabetes <- rio::import( "data/diabetes.csv")                      
DNA_forensic <- rio::import( "data/DNA_forensic.csv")              
factorial_expt <- rio::import( "data/factorial_expt.csv")          
howls <- rio::import( "data/howls.csv")                            
lizards <- rio::import( "data/lizards.csv")                       
lobster <- rio::import( "data/lobster.csv")                        
mussel_metabolomics <- rio::import( "data/mussel_metabolomics.csv")
paua <- rio::import( "data/paua.csv")                              
pitfalls <- rio::import( "data/pitfalls.csv")                      
plant_vigour <- rio::import( "data/plant_vigour.csv")              
Pokemon <- rio::import( "data/Pokemon.csv")                        
rats_crd_AUC <- rio::import( "data/rats_crd_AUC.csv")              
rcbd <- rio::import( "data/rcbd.csv")                              
split_plot <- rio::import( "data/split_plot.csv")
```


```{r codebook}
library(codebook)
codebook(abalone_subset, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )     
codebook(ACIAR, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )              
codebook(athletes, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )          
codebook(autism, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )             
codebook(biomarker, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )          
codebook(crd_rats_data, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )      
codebook(diabetes, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )           
codebook(DNA_forensic, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )       
codebook(factorial_expt, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )     
codebook(howls, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )              
codebook(lizards, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )            
codebook(lobster, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )            
codebook(mussel_metabolomics, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )
codebook(paua, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )               
codebook(pitfalls, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )           
codebook(plant_vigour, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )       
codebook(Pokemon, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )            
codebook(rats_crd_AUC, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )      
codebook(rcbd, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )               
codebook(split_plot, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE )         
```