---
title: "Codebook"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually makes debugging easier, and sometimes half a codebook
                # is better than none
  echo = FALSE  # don't show the R code
)
ggplot2::theme_set(ggplot2::theme_bw())
pander::panderOptions("table.split.table", Inf)
```

```{r}
files <- list.files("data", pattern = ".csv", full = TRUE)
names <- stringr::str_remove(list.files("data", pattern = ".csv"), ".csv")
for (i in 1:length(files)) {
     assign(names[i], rio::import(file = files[i]))
}
## can't figure out eval, pasre, codebook method, so let's go with this janky solution
## copying and pasting output to code chunk below :'-(
## paste("codebook::codebook(", names, 
     ## ", metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE)", sep = "", collapse = ";")

```
```{r}
codebook::codebook(abalone, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(aciar, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(antipodes, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(autism, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(biomarker, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(cannabis, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(darwin, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(dicots_proportions, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(dna_forensic, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(howls, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(lizards, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(lobster, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(medley, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(munsingen, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(mussel_metabolomics, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(pitfalls, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(plant_vigour, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(pokemon, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE);codebook::codebook(potato, metadata_json = FALSE, missingness_report = FALSE, detailed_variables = FALSE)

```

